### ISSUE TITLE
Feedback on software process

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/cs3892015team6#19]
Why is there Software Process and Reflection? Why do you have 2 sections of the same thing?

I will read your software process reflection when you will have had the time to review it as a team. For now it is too much of a draft and I cannot read it. 

![image](https://cloud.githubusercontent.com/assets/761057/7050575/50d3a324-ddf0-11e4-9aa0-035e86005331.png)

@dheerm @mrtrock @kb14375n

**Comment by dheerm** [comment]
I thought the process description was something different from the Reflection. They were listed as separate things so I put them in separate categories
